#pragma once

#include "NativeGameplayTags.h"

// Tags nativas usadas pelo codigo C++. Tags de conteudo (cooldown e cues de cada magia)
// ficam em Config/Tags/*.ini para nao exigir recompilacao.
namespace ArcanumTags
{
	// Escolas
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(School_Electricity);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(School_Fire);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(School_Energy);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(School_Necromancy);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(School_Blood);

	// Estados (concedidos por GameplayEffects)
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Paralyzed);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Burning);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Bleeding);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Cursed);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ArcaneCharge);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Wet);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ManaShield);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Channeling);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	// Chaves de SetByCaller
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_DamageMultiplier);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_ManaCost);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_HealthCost);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cooldown);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Duration);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Heal);

	// Abilities e recargas
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Spell);
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Global);

	// Cues genericos (os de cada magia vem do Data Asset)
	ARCANUMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Cast_School);
}
